# Generated by Django 3.2.7 on 2021-09-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210917_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
